### ISSUE TITLE
Fix gateway error

### ISSUE THREAD

**Issue by Arcoz0308** [Foxcord/foxcord#2]
Hello, for respect discord identify structure, in your websocket file replace $os value with process.platform and set the name of your librairy in $browser

Docs : https://discord.com/developers/docs/topics/gateway#identify-identify-connection-properties

**Comment by RemyK888** [comment]
Hello, I would like to inform you that your request has been taken into account and that our team is currently studying the issue.
We invite you to join our Discord server for more information! https://discord.gg/ZXnxZMwe5T
~ The Foxcord team

**Comment by DuAnti7423** [comment]
Well, he means u should switch these settings inside your websocket.ts [](https://prnt.sc/1g5i29v), os: to process.plattform and browser to foxcord.
As it said on the Docs he linked.

**Comment by RemyK888** [comment]
Thank you very much, @Arcoz0308 @DuAnti7423  that's what I understood, but these additions are still complex compared to our syntax, but we will probably correct this oversight by tonight.
~ The Foxcord team

**Comment by RemyK888** [comment]
Can I close this issue if you have no more requests?

**Comment by RemyK888** [comment]
Hello, I inform you that I just updated the code following your request, I close this issue.
